---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Baziri
description: Bazzite Nvidia open with Niri & DMS.

alt-tags:
  - workstation

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest 

blue-build-tag:
  - latest-installer

#  nushell-version
#  -latest

platforms:
  -linux-amd64

stages:
  - name: bongo-cat
  - image: 

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
